### PR TITLE
Remove weird \u0000 characters  when query

### PR DESCRIPTION
**Pull request by ThisTNTSquid**
A quick fix on the removing excessive space between characters when querying data that returns string data type

### CODE REVIEW

**Comment by ldilley** [comment]
Thank you for your contribution, ThisTNTSquid. Prior to merging this pull request, I would like to ask the following however:

1.) What weird characters are you observing in the version and what condition(s) cause it to manifest? The server should only ever send a decimal number we store as a string such as "1.7", "1.8", "1.9", etc. I have not yet encountered the symptom you are describing.

2.) If the MotD contains Unicode characters, this may be intended behavior depending on what the server administrator set as the "motd" value in the server.properties file for example. For instance, on my server, I have the following set in server.properties:

`
motd=\u2620 \u00A7c\u00A7lFrag Land\u00A7r \u2620\nwww.frag.land
`

Can you please elaborate more on what you want to see omitted here?

**Comment by ThisTNTSquid** [comment]
The thing I'm actually looking for is to remove the \u0000 character between each latter from strings
```javascript
var ms = require('./minestat');

function checkStatus(host, port) {
    ms.init(host, port, function(result)
    {
        // console.log("Minecraft server status of " + ms.address + " on port " + ms.port + ":");
        if(ms.online)
        {
            // console.log("Server is online running version " + ms.version + " with " + ms.current_players + " out of " + ms.max_players + " players.");
            // console.log("Message of the day: " + ms.motd);
            var status = {
                version: ms.version,
                port: ms.port,
                players: ms.current_players,
                max_player: ms.max_players,
                motd: ms.motd,
                address: ms.address
            }
            console.log(status);
        }
        else
        {
           return "Server is offline!";
        }
    });

}

checkStatus("localhost",25566);
```

This is the code used to retrieve server status and then print them out as a JSON string, and i get the result like this
```
{ version: '1\u0000.\u00001\u00001\u0000.\u00002',
  port: 25566,
  players: '0',
  max_player: '2\u00000',
  motd: 'A\u0000 \u0000M\u0000i\u0000n\u0000e\u0000c\u0000r\u0000a\u0000f\u0000t\u0000 \u0000S\u0000e\u0000r\u0000v\u0000e\u0000r',
  address: 'localhost' }
```
As you can see, it contains weird \u0000 between each character. The 2 small replacement I put in the code is used to remove those useless \u0000 which would become an extra space when used directly

**Comment by ThisTNTSquid** [comment]
Also, it is tested that this fix will only remove \u0000 characters which cause the problem, and will preserve any other unicode escaped characters (color codes are not affected)

**Comment by ldilley** [comment]
I apologize for the delay, TNT. I was taking it easy for Independence Day in the USA. After some more testing, it does look like the NUL character is stored in the char array between each character in a string. It was missed originally since console.log(<string>) and even the following loop:

```javascript
for (var i = 0, len = this.version.length; i < len; i++)
{
  process.stdout.write(this.version[i]);
}
```

does not reveal each unprintable character. However, if you print the length of the version string, it reports near double what is visibly printed (or in your JSON example.) Typically, the NUL byte is harmless. I can see it causing issues in the reported circumstances. I'll merge in your code changes. They look good. Thank you very much for your contribution again, ThisTNTSquid.

**Pull request merged**
